version: "3"

networks:
  sparknet:
    driver: bridge

services:

 postgres:
    image: postgres
    hostname: postgres
    networks:
     - sparknet
    expose:
     - 5432
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: mercanto
      POSTGRES_PASSWORD: mercanto
      POSTGRES_DB: mercanto
    volumes:
     - /tmp/docker/pgdata:/var/lib/postgresql/data

 cassandra:
    image: cassandra:3.0
    hostname: cassandra
    networks:
     - sparknet
    expose:
     - 7000 
     - 7001  
     - 7199
     - 9160
     - 9042
    ports:
     - 7199:7199
     - 9160:9160
     - 9042:9042
    volumes:
     - /tmp/docker/cassandra-1/data:/var/lib/cassandra

 cassandra-2:
    image: cassandra:3.0
    hostname: cassandra-2
    networks:
     - sparknet
    expose:
     - 7000
     - 7001   
     - 7199
     - 9160
     - 9042
    ports:
     - 17199:7199
     - 19160:9160
     - 19042:9042
    volumes:
     - /tmp/docker/cassandra-2/data:/var/lib/cassandra
    links:
     - cassandra
    environment:
      CASSANDRA_SEEDS: cassandra

 zookeeper:
    image: zookeeper:3.4
    hostname: zookeeper
    networks:
     - sparknet
    expose:
     - 2181
    ports:
     - 2181:2181

 kafka:
    image: ches/kafka
    hostname: kafka
    networks:
     - sparknet
    depends_on:
     - "zookeeper"
    expose:
     - 9092
     - 7203
    ports:
     - 9092:9092
     - 7203:7203
    environment:
      ZOOKEEPER_IP: zookeeper
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.1
      KAFKA_CREATE_TOPICS: "testrun:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
     - /tmp/docker/kafka/data:/data
     - /tmp/docker/kafka/logs:/logs

 spark-master:
    image: a2mz/spark-cluster
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    networks:
     - sparknet
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 0.0.0.0
      SPARK_DEPLOY_DEFAULTCORES: 1
    expose:
     - 4040
     - 7001
     - 7002
     - 7003
     - 7004
     - 7005
     - 7006
     - 7077
     - 6066
    ports:
     - 4040:4040
     - 6066:6066
     - 7077:7077
     - 8080:8080
    volumes:
     - /tmp/docker/spark-master/conf:/conf
     - /tmp/docker/spark-master/data:/tmp/data
     - /tmp/docker/spark-allnodes:/jar

 spark-worker-1:
    image: a2mz/spark-cluster
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
     - sparknet
    depends_on:
     - "spark-master"
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 0.0.0.0
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    expose:
     - 7012
     - 7013
     - 7014
     - 7015
     - 7016
     - 8881
    ports:
     - 8081:8081
    volumes:
     - /tmp/docker/spark-worker-1/config:/conf
     - /tmp/docker/spark-worker-1/data:/tmp/data
     - /tmp/docker/spark-allnodes:/jar

 spark-worker-2:
    image: a2mz/spark-cluster
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
     - sparknet
    depends_on:
     - "spark-master"
    hostname: spark-worker-2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 0.0.0.0
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
    expose:
     - 7012
     - 7013
     - 7014
     - 7015
     - 7016
     - 8882
    ports:
     - 8082:8082
    volumes:
     - /tmp/docker/spark-worker-2/config:/conf
     - /tmp/docker/spark-worker-2/data:/tmp/data
     - /tmp/docker/spark-allnodes:/jar

 spark-worker-3:
    image: a2mz/spark-cluster
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
     - sparknet
    depends_on:
     - "spark-master"
    hostname: spark-worker-3
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 0.0.0.0
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8883
      SPARK_WORKER_WEBUI_PORT: 8083
    expose:
     - 7012
     - 7013
     - 7014
     - 7015
     - 7016
     - 8883
    ports:
     - 8083:8083
    volumes:
     - /tmp/docker/spark-worker-3/config:/conf
     - /tmp/docker/spark-worker-3/data:/tmp/data
     - /tmp/docker/spark-allnodes:/jar
